# Site/SEO settings
email: JLSaunders987@gmail.com
baseurl: "/blog"
paginate: 12
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/
google_analytics:

name: Jonny Saunders
title: Blog
description: >
  Things i gone and done
url: "https://jon-e.net"
twitter_username: json_dirs
default_img: /assets/images/nlight.png
social:
  - name: twitter
    url: https://twitter.com/json_dirs
  - name: github
    url: https://github.com/sneakers-the-rat

# Contact settings
contact_img: /assets/images/emailin_me.gif
formcarry: https://formcarry.com/s/x7yoFO6sk0n

# Disqus settings
disqus: jon-e

# MailChimp settings
# mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
# mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Jonny Saunders
    bio: bad at programming and neuroscience in beautiful Oregon.
    url: http://jon-e.net

# configure jekyll scholar
scholar:
  source: ./assets/references
  bibliography: blog.bib
  style: national-science-foundation-grant-proposals

# Build settings
markdown: kramdown
highlighter: rouge
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-jupyter-notebook
  - jekyll-toc
  - jekyll/scholar

toc:
  - max_level: 1

compress_html:
  clippings: all
  comments: all
  startings: [html, body]
  # startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - '*.Rmd'

colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

